### ISSUE TITLE
少日逢春如病酒 · 廢話集

### ISSUE THREAD

**Issue by inchei** [inchei/inchei.github.io#4]
https://inchei.github.io/2017/11/18/sick-wine/

**Comment by dimpurr** [comment]
```bash
git log  -p -- _posts/2017-11-18-sick-wine.md
````

- Git file track can be removed by this way: http://blog.dimpurr.com/yiban-report-17/#dm_bfg .
- Github ISSUE can't be deleted, but you can close it, or edit it and pretend to be completely different thing.
